### ISSUE TITLE
when you run block-explorer the opening details of first transaction - broke `explorer.mynetwork.com` container

### ISSUE THREAD

**Issue by andrii482** [482solutions/woden-explorer#1]
`explorer.mynetwork.com      | [2020-09-09T12:19:03.583] [DEBUG] dbroutes - { txhash:
explorer.mynetwork.com      |    '47cf5429241cafc98cb9091d18abae00cf6e0d1a4c1048dbcb1dfe33ab49cd53',
explorer.mynetwork.com      |   validation_code: 'ENDORSEMENT_POLICY_FAILURE',
explorer.mynetwork.com      |   payload_proposal_hash:
explorer.mynetwork.com      |    '0e74188860694c724063ef7b9092b65cf80dba461c1fa3da83f82034a3f72d04',
explorer.mynetwork.com      |   creator_msp_id: '482solutions',
explorer.mynetwork.com      |   endorser_msp_id: '{"482solutions"}',
explorer.mynetwork.com      |   chaincodename: 'wodencc',
explorer.mynetwork.com      |   type: 'ENDORSER_TRANSACTION',
explorer.mynetwork.com      |   createdt: '2020-09-09T12:18:25.731Z',
explorer.mynetwork.com      |   read_set:
explorer.mynetwork.com      |    [ { chaincode: 'lscc', set: [Array] },
explorer.mynetwork.com      |      { chaincode: 'wodencc', set: [] } ],
explorer.mynetwork.com      |   write_set:
explorer.mynetwork.com      |    [ { chaincode: 'lscc', set: [] },
explorer.mynetwork.com      |      { chaincode: 'wodencc', set: [Array] } ],
explorer.mynetwork.com      |   channelname: 'testchannel' }
explorer.mynetwork.com      | [2020-09-09T12:19:21.105] [DEBUG] dbroutes - { txhash:
explorer.mynetwork.com      |    'b000270a4a8ddd9eb7bcbd8dfe043b93d2118322198ce783310de9cdd67158a1',
explorer.mynetwork.com      |   validation_code: 'ENDORSEMENT_POLICY_FAILURE',
explorer.mynetwork.com      |   payload_proposal_hash:
explorer.mynetwork.com      |    '7c107a608b42121879d8984744e6b1fcefc258dfc38fcb744bffd1bf34c0d9c3',
explorer.mynetwork.com      |   creator_msp_id: '482solutions',
explorer.mynetwork.com      |   endorser_msp_id: '{"482solutions"}',
explorer.mynetwork.com      |   chaincodename: 'lscc',
explorer.mynetwork.com      |   type: 'ENDORSER_TRANSACTION',
explorer.mynetwork.com      |   createdt: '2020-09-09T10:29:17.365Z',
explorer.mynetwork.com      |   read_set:
explorer.mynetwork.com      |    [ { chaincode: 'lscc', set: [Array] },
explorer.mynetwork.com      |      { chaincode: 'wodencc', set: [] } ],
explorer.mynetwork.com      |   write_set:
explorer.mynetwork.com      |    [ { chaincode: 'lscc', set: [Array] },
explorer.mynetwork.com      |      { chaincode: 'wodencc', set: [Array] } ],
explorer.mynetwork.com      |   channelname: 'testchannel' }
explorer.mynetwork.com      | [2020-09-09T12:19:21.110] [ERROR] main - <<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
explorer.mynetwork.com      | [2020-09-09T12:19:21.110] [ERROR] main - SyntaxError: Unexpected token  in JSON at position 1
explorer.mynetwork.com      |     at JSON.parse (<anonymous>)
explorer.mynetwork.com      |     at dbCrudService.getTransactionByID.then.row (/opt/explorer/app/rest/dbroutes.js:94:47)
explorer.mynetwork.com      |     at process._tickCallback (internal/process/next_tick.js:68:7)
explorer.mynetwork.com      | [2020-09-09T12:19:23.112] [INFO] main - Received kill signal, shutting down gracefully
explorer.mynetwork.com      | [2020-09-09T12:19:23.121] [INFO] Platform - <<<<<<<<<<<<<<<<<<<<<<<<<< Closing explorer  >>>>>>>>>>>>>>>>>>>>>
explorer.mynetwork.com      | [2020-09-09T12:19:23.122] [INFO] main - Closed out connections
explorer.mynetwork.com      | [2020-09-09T12:19:23.123] [INFO] Sync - <<<<<<<<<<<<<<<<<<<<<<<<<< Closing client processor >>>>>>>>>>>>>>>>>>>>>
explorer.mynetwork.com      | [2020-09-09T12:19:23.125] [DEBUG] FabricEvent - disconnectEventHubs()
explorer.mynetwork.com      | [2020-09-09T12:19:23.126] [DEBUG] FabricEvent - disconnectChannelEventHub(testchannel)
explorer.mynetwork.com exited with code 1
`

![block_explorer_2020-09-0915:23:06](https://user-images.githubusercontent.com/61418776/92597690-7045a600-f2b0-11ea-8cfc-a2cd2e409b5c.png)

**Comment by andrii482** [comment]
when you try to open details of `TX Id  b00027...`  - explorer crushed.

All other transaction details  open's correct.

**Comment by andrii482** [comment]
https://github.com/search?q=org%3A482solutions+lscc&type=Code
